### PR TITLE
Added support for nesting in section names

### LINKED ISSUE #43: Feature: support nested sections
This is a feature present in the zend ini parser (PHP core library)

e.g.
```ini
[normal]
item=0

[nested.child1]
item1=1

[nested.child2]
item2=2
```

ideally becomes:
```json
{
  "normal": {
    "item":0
  },
  "nested": {
    "child1": {
      "item1":1
    },
    "child2": {
      "item2":2
    }
  }
}
```

currently this is the output:
```json
{
  "normal": {
    "item":0
  },
  "nested.child1": {
    "item1":1
  },
  "nested.child2": {
    "item2":2
  }
}
```

### PR DESCRIPTION
**Pull request by evangelion1204**
Supports nesting in section names.

Closes #43 #44

### CODE REVIEW

**Comment by evangelion1204** [comment]
@rijnhard please have a look

**Comment by rijnhard** [comment]
It doesn't need a toggle if the version is bumped and a breaking change is noted. Otherwise it could break existing use.
Looks good, tests will cover it too. Nice. Much simpler then what I did.

**Comment by evangelion1204** [comment]
I was wondering too, as the lib should be compatible with Zend I would just bump the minor version and also add a toggle to disable.

**Comment by rijnhard** [comment]
I don't see a test case for zero prefixes?

**Comment by evangelion1204** [comment]
I just added tests to the filter see here if its suitable. https://github.com/evangelion1204/multi-ini/blob/master/test/filter_spec.js#L115-L132

**Pull request merged**
