### PR TITLE
Added test to show error

### PR DESCRIPTION
**Pull request by evangelion1204**
Fixes introduced bug of #12

@sanglier91 could you check my example test I added? I created a the example file but don't get an error, maybe you use different params then me and/or a different node version or even io.js?

### CODE REVIEW

**Comment by sanglier91** [comment]
Your example test looks good (but I didn't test it, can you tell me how to run your unit tests ? ).

This is my npm version:

```
{ http_parser: '1.0',
  node: '0.10.28',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.27',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1g',
  npm: '1.4.9',
  CDT: '0.1.0' }
```

**Comment by evangelion1204** [comment]
Thanks, I will add different node versions to the tests. In case you want to execute them you currently need Grunt and just run `grunt test` in the repo root. Are you running under windows?

**Comment by sanglierquipue** [comment]
Hi, I run the test case and get no error.

I don't know if it can help you but I change the following lines (in `multi-ini-class.js`)  from:

`_ref = this.getMultiKeyValue(line), key = _ref[0], value = _ref[1];` (line 231)
and
`_ref1 = this.getMultiLineEndValue(line), value = _ref1[0], status = _ref1[1];` (line 237)

to 

`_ref = this.getMultiKeyValue(trimmedLine), key = _ref[0], value = _ref[1];`
and
`_ref1 = this.getMultiLineEndValue(trimmedLine), value = _ref1[0], status = _ref1[1];`

and now it works.

**Comment by evangelion1204** [comment]
Yes, but now the lines are trimmed again. But I know now, that its the line break encoding of windows CRLF. I just tested with Unix line breaks.

**Pull request merged**
